language : generic
sudo: required
services:
 -docker
 before-install:
  -docker build -t 2smooth4u/docker-react -f Dockerfile.dev
 script:
  - docker run -e CI=true 2smooth4u/docker-react npm run test -- -- coverage
